service: serverlessphoenix
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  environment:
    tableName: ${self:custom.tableName}
    PLC_TABLE: ${self:custom.PLC_TABLE}
  apiGateway: {
    shouldStartNameWithService: true
  }
  region: eu-central-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Resource: arn:aws:dynamodb:eu-central-1:114100681027:table/myPLC
      Resource: '*'
  
custom:
    PLC_TABLE: myPLC
    tableName: WebsocketUsers

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: get
          cors: true
      - http: 
          path: /{proxy+}
          method: any
          cors: true 
  myIoT:
    handler: myIoT.handler
    events:
      - iot:
          name: 'myIotEvent'
          sql: "SELECT * FROM 'MyPLCNext/temperature'"
          description: 'My IoT Event Description'
  postData:
    handler: postData.handler
    events:
      - http:
          path: add-temerature/{ID}
          method: POST
          cors: true
  websocket-connect:
    handler: websockets/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-default:
    handler: websockets/default.handler
    events:
      - websocket:
          route: $default
  websocket-message:
    handler: websockets/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    WebsocketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

          