service: serverlessphoenix
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  environment:
    PLC_TABLE: ${self:custom.PLC_TABLE}
  apiGateway: {
    shouldStartNameWithService: true
  }
  region: eu-central-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: '*'
  
custom:
    PLC_TABLE: PLCNextTable

functions:
  app:
    handler: index.handler
    events:
      - http: 
          path: /
          method: get
          cors: true
      - http: 
          path: /{proxy+}
          method: any
          cors: true 
  plcIoT:
    handler: IotCoreRules/plcNextRule.handler
    events:
      - iot:
          name: 'PLCEvent'
          sql: "SELECT * FROM 'MyPLCNext'"
          description: 'Get a data set from PLCNext'


          